### ISSUE TITLE
安装过程问题求助

### ISSUE THREAD

**Issue by Childish-Ghost** [Yutong-gannis/ETSAuto#11]
CUDA完成安装 环境报错

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running. This can also be happening if non-NVIDIA GPU is running as primary display, and NVIDIA GPU is in WDDM mode.

**Comment by Childish-Ghost** [comment]
![image](https://user-images.githubusercontent.com/87593016/215739701-ddc03599-d543-432b-a5b8-c5e0c5454eff.png)
补充
![image](https://user-images.githubusercontent.com/87593016/215739786-7faf40da-3c1d-4e5d-91a9-8b758b337550.png)

**Comment by Yutong-gannis** [comment]
@Childish-Ghost 检查一下你的显卡驱动安装好了吗
