### ISSUE TITLE
尝试构建 YOLOV6 的 TensorRT 文件时发生错误

### ISSUE THREAD

**Issue by 1257164071** [Yutong-gannis/ETSAuto#14]
PS E:\ai\eu2\auto2\Self-driving-Truck-in-Euro-Truck-Simulator2> python3.8.exe .\tools\export.py -o .\engines\yolov6s_bdd_60.onnx -e .\engines\yolov6s_bdd_60.engine --end2end
Namespace(calib_batch_size=8, calib_cache='./calibration.cache', calib_input=None, calib_num_images=5000, conf_thres=0.4, end2end=True, engine='.\\engines\\yolov6s_bdd_60.engine', iou_thres=0.5, max_det=100, onnx='.\\engines\\yolov6s_bdd_60.onnx', precision='fp16', verbose=False, workspace=1)
[02/10/2023-02:36:49] [TRT] [I] [MemUsageChange] Init CUDA: CPU +223, GPU +0, now: CPU 11354, GPU 1385 (MiB)
[02/10/2023-02:36:50] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU -40, GPU +2, now: CPU 11375, GPU 1387 (MiB)
.\tools\export.py:109: DeprecationWarning: Use set_memory_pool_limit instead.
  self.config.max_workspace_size = workspace * (2 ** 30)
[02/10/2023-02:36:50] [TRT] [W] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Network Description
Input 'images' with shape (1, 3, 640, 640) and dtype DataType.FLOAT
Output 'outputs' with shape (1, 8400, 15) and dtype DataType.FLOAT
.\tools\export.py:143: DeprecationWarning: Use network created with NetworkDefinitionCreationFlag::EXPLICIT_BATCH flag instead.
  self.builder.max_batch_size = self.batch_size
Building fp16 Engine in E:\ai\eu2\auto2\Self-driving-Truck-in-Euro-Truck-Simulator2\engines\yolov6s_bdd_60.engine
.\tools\export.py:242: DeprecationWarning: Use build_serialized_network instead.
  with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
[02/10/2023-02:36:50] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +158, GPU +50, now: CPU 11573, GPU 1437 (MiB)
[02/10/2023-02:36:51] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +140, GPU +50, now: CPU 11713, GPU 1487 (MiB)
[02/10/2023-02:36:51] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[02/10/2023-02:37:39] [TRT] [E] 1: [convolutionRunner.cpp::nvinfer1::rt::task::CaskConvolutionRunner::execute::213] Error Code 1: Cask (Cask convolution execution)
Traceback (most recent call last):
  File ".\tools\export.py", line 288, in <module>
    main(args)
  File ".\tools\export.py", line 249, in main
    builder.create_engine(args.engine, args.precision, args.calib_input, args.calib_cache, args.calib_num_images,
  File ".\tools\export.py", line 242, in create_engine
    with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
AttributeError: __enter__
PS E:\ai\eu2\auto2\Self-driving-Truck-in-Euro-Truck-Simulator2>

**Comment by 1257164071** [comment]
能否提供一下构建完的yolov6s_bdd_60.engine, 环境一致就是报错，全网都搜遍了也没办法解决

**Comment by Yutong-gannis** [comment]
@1257164071 engine文件只能在自己电脑上构建

**Comment by Yutong-gannis** [comment]
@1257164071 试一下trtexec能不能转换

**Comment by 1257164071** [comment]
![fb5b4d4d385d02078b8996b5cae49ed2](https://user-images.githubusercontent.com/25576221/218030017-41308a56-0fd3-46c4-83a8-989e9965cd5b.png)

**Comment by 1257164071** [comment]
trtexec.exe --onnx=yolov6s_bdd_60.onnx --saveEngine=model.engine --fp16 --workspace=3000 --buildOnly
 执行就会显示着个错误，是我环境装的有问题吗，

**Comment by ywjno** [comment]
感觉是cudnn的版本出错了

**Comment by 1257164071** [comment]
我把系统重装了一遍，还是同样的错误，之后常识升级了下trt总算是可以顺利生成engine文件了
但是现在又遇到一个问题。用trtexec转换的时候报的错
trtexec --onnx=./engines/llamas_dla34_tmp.onnx --saveEngine=./engines/llamas_dla34.engine
![image](https://user-images.githubusercontent.com/25576221/218248008-a8b00a7a-ec40-4771-93ed-738be003c444.png)
能帮忙看一下吗，万分感谢

**Comment by 1257164071** [comment]
升级完CUDA11和更高版本的TRT cudaa就正常了

**Comment by HLeonHong** [comment]
> 升级完CUDA11和更高版本的TRT cudaa就正常了

我感觉我也要试试这个思路

**Comment by HLeonHong** [comment]
> 能否提供一下构建完的yolov6s_bdd_60.engine, 环境一致就是报错，全网都搜遍了也没办法解决

请问题主, “engine文件只能在自己电脑上构建”
 ______  ______  ______  ______  ______  ______ 
作者说的“下载 [onnx 权重文件](https://github.com/Yutong-gannis/Self-driving-Truck-in-Euro-Truck-Simulator2/releases)，放在 <PROJECT_PATH>/engines 文件夹下（手动创建）。”
 ______  ______  ______  ______  ______  ______ 

是怎么理解, 权重文件下载下来是放在engines文件夹吧? 
然后engine文件它会构建在哪里?

**Comment by 1257164071** [comment]
就是你建一个engines文件夹吧.onnx后缀的丢进去，就可以通过命令生成一个你自己的yolov6s_bdd_60.onnx

**Comment by HLeonHong** [comment]
> 就是你建一个engines文件夹吧.onnx后缀的丢进去，就可以通过命令生成一个你自己的yolov6s_bdd_60.engine

好的, 明白了. 通过命令生成后会覆盖原先放进去的.

**Comment by 1257164071** [comment]
要是升级的话会遇到一个score_activation错误，在  export.py里的 fc = trt.PluginFieldCollection(fc) 前面加上一行
            fc.append(trt.PluginField("score_activation", np.array([0], dtype=np.int32), trt.PluginFieldType.INT32))
就可以生成了

**Comment by HLeonHong** [comment]
> fc.append(trt.PluginField("score_activation", np.array([0], dtype=np.int32), trt.PluginFieldType.INT32))

还真遇到了

**Comment by GIN-zhao** [comment]
换 CUDA11.6  CUDNN 8.7   tensorrt 8.6
