### ISSUE TITLE
此项目无法在Linunx（Ubuntu）平台上部署吗？

### ISSUE THREAD

**Issue by CrazyMustard-404** [Yutong-gannis/ETSAuto#17]
作者您好，由于我跑模型的机器为Linux平台，在装环境的时候遇到此包（pywin32）无法安装，所以此项目是否只能在windows平台部署？And在无CPU设备上是否也无法跑起来？

**Comment by Yutong-gannis** [comment]
@CrazyMustard-404 pywin32只支持Windows，你需要自己编写一个Linux获取屏幕截图的函数，然后替换掉main.py的113行

**Comment by CrazyMustard-404** [comment]
> @CrazyMustard-404 pywin32只支持Windows，你需要自己编写一个Linux获取屏幕截图的函数，然后替换掉main.py的113行

非常感谢您的回答，那我可否直接将一段视频流传入模型进行推理？然后将每一帧的控制操作print出来呢？

**Comment by Yutong-gannis** [comment]
@CrazyMustard-404 只需要把你获取的每帧图像赋给I’m就可以了

**Comment by CrazyMustard-404** [comment]
> 

明白了，非常感谢您的回答。
