### ISSUE TITLE
detect画面和游戏画面不同步

### ISSUE THREAD

**Issue by HLeonHong** [Yutong-gannis/ETSAuto#19]
成功运行后, 识别的窗口显示的画面和游戏运行的画面不同步, 识别的窗口画面很慢

这是性能导致的吗? 

麻烦作者查查这问题的原因

**Comment by Yutong-gannis** [comment]
@HLeonHong  我的是笔记本上的rtx1650，可以跑到6帧，你有多少帧

**Comment by HLeonHong** [comment]
我重新部署但目前在

> @HLeonHong 我的是笔记本上的rtx1650，可以跑到6帧，你有多少帧

二次部署已经能运行了
也有开新的issue作分享
