### ISSUE TITLE
车道线后处理那块不是很理解，希望得到帮助

### ISSUE THREAD

**Issue by reverse-2020** [Yutong-gannis/ETSAuto#20]
```
def bev_lane(lanes, CAM, lines_cls, vanish_point):
    # CAM.update_intrinsic(vanish_point)  #根据灭点坐标的相机外参修正
    bev_lanes = []
    for i in range(len(lanes)):
        if len(lanes[i]) < 10:  # 过滤点数小于10的线
            continue
        bev_lane_pts = []
        bev_xy = [] # 拟合前
        for pt in lanes[i]:
            pt = list(pt)
            pt[1] = 720 - pt[1] #为什么要-pt[1]?
            bev_pt = CAM.pixel_to_world(pt).tolist() #像素坐标系转世界坐标系，为什么纵是X轴，横是Y轴？
            if 470 - bev_pt[0][1]/2 <= 250 or 470 - bev_pt[0][1]/2 >= 500:  #这段代码的作用？
                continue
            bev_xy.append([int(bev_pt[0][0]/5)+400, 470 - int(bev_pt[0][1]/1.8)]) #这段代码不是很理解
        bev_xy = np.array(bev_xy).T
        fit = np.polyfit(bev_xy[:][1], bev_xy[:][0], 3)  # 三次函数拟合
        bev_y = np.linspace(250, 470, 20)  # 为了减少计算量，采样点减少为20个
        bev_x = fit[0] * bev_y ** 3 + fit[1] * bev_y ** 2 + fit[2] * bev_y + fit[3]
        for j in range(20):
            if np.abs(bev_x[j]-400) >= 60: continue #这段代码的作用
            bev_lane_pts.append((int(bev_x[j]), int(bev_y[j])))
        if len(bev_lane_pts) >= 1: # 之前过滤了一次距离，可能全过滤掉了
            bev_line = Bev_Lane(lines_cls[i], 5, fit, bev_lane_pts[-1], bev_lane_pts[0], bev_lane_pts)  # 封装bev车道线信息
            bev_lanes.append(bev_line)
    return bev_lanes
```
另外我想问下，这个bev_lanes 名称的含义是什么，指的是在bev图上的lanes吗？另外我想知道相机内参 self.T = [0, 0, 300] # 机身坐标与地面坐标间的平移向量，这个300指的是300mm吗，也就是在z轴平移了300mm？

**Comment by reverse-2020** [comment]
还有一个问题，计算灭点的作用是什么，或者说计算灭点的意义- -

**Comment by Yutong-gannis** [comment]
@reverse-2020 bev_lanes是仿照Apollo对bev下车道线信息进行的封装，对象的定义应该在前面。内外参是猜的，只能保证大致合理，灭点计算没用上，我是希望通过灭点去修正相机参数的

**Comment by Yutong-gannis** [comment]
@reverse-2020 bev_lanes是仿照Apollo对bev下车道线信息进行的封装，对象的定义应该在前面。内外参是猜的，只能保证大致合理，灭点计算没用上，我是希望通过灭点去修正相机参数的

**Comment by reverse-2020** [comment]
> @reverse-2020 bev_lanes是仿照Apollo对bev下车道线信息进行的封装，对象的定义应该在前面。内外参是猜的，只能保证大致合理，灭点计算没用上，我是希望通过灭点去修正相机参数的

好的，我去看下，可以贴个url嘛，下面有一些代码不太懂，希望up解疑答惑下

#1
pt[1] = 720 - pt[1] #为什么要-pt[1]?

#2 
bev_pt = CAM.pixel_to_world(pt).tolist() #像素坐标系转世界坐标系，为什么纵是X轴，横是Y轴？

#3
if 470 - bev_pt[0][1]/2 <= 250 or 470 - bev_pt[0][1]/2 >= 500:  #这段代码的作用？
                continue

#4
bev_xy.append([int(bev_pt[0][0]/5)+400, 470 - int(bev_pt[0][1]/1.8)]) #这段代码不是很理解

**Comment by Yutong-gannis** [comment]
@reverse-2020 
#1 像素点纵坐标是从上向下的，而坐标系转换是绕下面的轴旋转的
#2 可能是我可能是交换过一下
#3 过滤一些太远的点
#4 除的相当于是做了一些缩放，加的四百是横坐标中心

**Comment by Yutong-gannis** [comment]
@reverse-2020 https://github.com/Yutong-gannis/Self-driving-Truck-in-Euro-Truck-Simulator2/blob/5c1e446ca6f911ef9eae6710a41a0796f7dc2063/Perception/LaneDetection/postprocess.py#L7-L26

**Comment by reverse-2020** [comment]
> @reverse-2020
> 
> https://github.com/Yutong-gannis/Self-driving-Truck-in-Euro-Truck-Simulator2/blob/5c1e446ca6f911ef9eae6710a41a0796f7dc2063/Perception/LaneDetection/postprocess.py#L7-L26

谢谢up，太仔细了 ，我去review下
