### ISSUE TITLE
Linux下VJoy和pyvjoy的替代问题

### ISSUE THREAD

**Issue by YoghourtM** [Yutong-gannis/ETSAuto#23]
作者您好，当我调试到最后一步的时候，发现pyvjoy使用from ctypes import wintypes，使用的都是Windows上的API，所以项目无法在Linux上运行，请问您知道Linux上有什么vjoy的替代品么？或者可以使用什么其他方法（比如键盘直接输入）进行控制么？

**Comment by Yutong-gannis** [comment]
@YoghourtM 我尝试过直接键盘输入，结果控制不了

**Comment by Yutong-gannis** [comment]
@YoghourtM 或许你可以看看这个仓库https://github.com/zvxryb/Linux-Virtual-Joystick

**Comment by YoghourtM** [comment]
> @YoghourtM 或许你可以看看这个仓库https://github.com/zvxryb/Linux-Virtual-Joystick

好吧，或许我可以再试试别的方法

**Comment by CrazyMustard-404** [comment]
> 

你好，请问有新的解决办法了吗

**Comment by YoghourtM** [comment]
> > 
> 
> 你好，请问有新的解决办法了吗

没有找到，所以我还是回到Windows平台了

**Comment by Yutong-gannis** [comment]
@YoghourtM @CrazyMustard-404 
不好意思，现在不打算兼容linux了，因为贡献者写的后续的控制代码都是基于windows的，后续确实没法改了

**Comment by j22525** [comment]
好像用
https://github.com/tuomasjjrasanen/python-uinput
移植到 Linux 挺方便的
