### ISSUE TITLE
模型似乎很喜欢应急车道

### ISSUE THREAD

**Issue by YoghourtM** [Yutong-gannis/ETSAuto#34]
当程序运行时，纵向控制的预测点总是位于车辆最右侧，所以总是被横向控制拉过去
![ADE(XRC8W_K2S7L8IIE S6L](https://user-images.githubusercontent.com/52021115/227422836-a7162291-7ef8-4a73-bb71-9166bc97b4f4.jpg)
但是并不会撞墙，并且会在应急车道中稳定行驶
![OJ HPA%KGVQ)RY `A`F${(1](https://user-images.githubusercontent.com/52021115/227423089-060d5152-8ab7-4b61-8d5b-2778163b1dcd.jpg)
想请教一下解决方法

**Comment by Yutong-gannis** [comment]
@YoghourtM 游戏窗口向左边移一点

**Comment by YoghourtM** [comment]
@Yutong-gannis 谢谢，现在已经解决了，我大概知道要把窗口放哪儿了
